Repository work-flow-helper/work-flow-helper, pull requests merged in 2024-07, with the labels that each got.

#17 Feat/2 카드 등록 기능
  src/main/java/com/sparta/workflowhelper/domain/card/adapter/CardAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/card/controller/CardController.java
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardSimpleResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/entity/Card.java
  src/main/java/com/sparta/workflowhelper/domain/card/service/CardService.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/adapter/ProjectMemberAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/adapter/UserBoardMappingAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/entity/ProjectMember.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/repository/ProjectMemberRepository.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/repository/UserBoardMappingRepository.java
  src/main/java/com/sparta/workflowhelper/domain/project/entity/Project.java
  src/main/java/com/sparta/workflowhelper/domain/stage/adapter/StageAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/user/adapter/UserAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/user/entity/User.java
  src/main/java/com/sparta/workflowhelper/domain/worker/adapter/WorkerAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/worker/dto/WorkerInfoDto.java
  src/main/java/com/sparta/workflowhelper/domain/worker/entity/Worker.java
  src/main/java/com/sparta/workflowhelper/domain/worker/repository/WorkerRepository.java
  src/main/java/com/sparta/workflowhelper/global/common/dto/CommonErrorResponseDto.java
  src/main/java/com/sparta/workflowhelper/global/common/dto/CommonResponseDto.java
  src/main/java/com/sparta/workflowhelper/global/config/AuthConfig.java
  src/main/java/com/sparta/workflowhelper/global/config/SecurityConfig.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/ProjectMemberNotFoundException.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/StageNotFoundException.java
  src/main/java/com/sparta/workflowhelper/global/exception/errorcodes/NotFoundErrorCode.java
  src/main/java/com/sparta/workflowhelper/global/exception/handler/GlobalExceptionHandler.java
Labels: 📰feature

#39 Refactor/36 refactor 카드 순서 배정 기능 수정
  api-test/user-test.http
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardPositionRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/entity/Card.java
  src/main/java/com/sparta/workflowhelper/domain/card/repository/CardQueryRepository.java
  src/main/java/com/sparta/workflowhelper/domain/card/service/CardService.java
Labels: 🐞bug, 🔧fix, 🔨refactor

#63 Domain/8 stage main
  api-test/user-test.http
  src/main/java/com/sparta/workflowhelper/domain/stage/adapter/StageAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/stage/controller/StageController.java
  src/main/java/com/sparta/workflowhelper/domain/stage/dto/StagePositionRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/stage/dto/StageRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/stage/dto/StageResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/stage/entity/Stage.java
  src/main/java/com/sparta/workflowhelper/domain/stage/http/Stage.http
  src/main/java/com/sparta/workflowhelper/domain/stage/repository/StageRepository.java
  src/main/java/com/sparta/workflowhelper/domain/stage/service/StageService.java
  src/main/java/com/sparta/workflowhelper/global/common/dto/CommonResponseDto.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/ProjectNotFoundException.java
  src/main/java/com/sparta/workflowhelper/global/exception/errorcodes/NotFoundErrorCode.java
Labels: 🐞bug, 📰feature, 🔧fix, 🔨refactor

#64 🎉 FEAT: 로그인, 회원가입, 메인, 카드 html 작성
  src/main/resources/static/index.html
  src/main/resources/static/main.html
  src/main/resources/static/signup.html
Labels: 📰feature

#65 Feat/project function
  src/main/java/com/sparta/workflowhelper/domain/mapping/adapter/ProjectMemberAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/entity/ProjectMember.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/repository/ProjectMemberRepository.java
  src/main/java/com/sparta/workflowhelper/domain/project/adapter/ProjectAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/project/controller/ProjectController.java
  src/main/java/com/sparta/workflowhelper/domain/project/dto/ProjectRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/project/dto/ProjectResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/project/entity/Project.java
  src/main/java/com/sparta/workflowhelper/domain/project/service/ProjectService.java
  src/main/java/com/sparta/workflowhelper/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/workflowhelper/global/config/SecurityConfig.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/CustomAccessDeniedException.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/ProjectNotFoundException.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/globalexceptions/ProjectNotFoundException.java
Labels: 📰feature

#66 Domain/48 profile main
  src/main/java/com/sparta/workflowhelper/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/workflowhelper/domain/auth/dto/AuthRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/auth/service/AuthService.java
  src/main/java/com/sparta/workflowhelper/domain/user/adapter/UserAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/user/controller/UserController.java
  src/main/java/com/sparta/workflowhelper/domain/user/dto/UpdateProfileRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/user/dto/UserPagedResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/user/entity/User.java
  src/main/java/com/sparta/workflowhelper/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/workflowhelper/domain/user/service/UserService.java
  src/main/java/com/sparta/workflowhelper/global/common/enums/UserStatus.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/AlreadyWithdrawnException.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/ProfileAccessException.java
  src/main/java/com/sparta/workflowhelper/global/exception/errorcodes/AlreadyWithdrawnErrorCode.java
  src/main/java/com/sparta/workflowhelper/global/exception/errorcodes/ProfileAccessErrorCode.java
  src/main/java/com/sparta/workflowhelper/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/sparta/workflowhelper/global/jwt/JwtProvider.java
Labels: 📰feature, 🔨refactor

#68 Domain/1 card main
  api-test/user-test.http
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/dto/CardUpdatedRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/card/service/CardService.java
  src/main/java/com/sparta/workflowhelper/domain/stage/entity/Stage.java
  src/main/java/com/sparta/workflowhelper/global/config/SecurityConfig.java
Labels: 🔨refactor

#71 🐛 BUGFIX: 프로젝트 생성시 중복 멤버 추가 불가능
  src/main/java/com/sparta/workflowhelper/domain/mapping/adapter/ProjectMemberAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/mapping/repository/ProjectMemberRepository.java
  src/main/java/com/sparta/workflowhelper/domain/project/adapter/ProjectAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/project/service/ProjectService.java
  src/main/java/com/sparta/workflowhelper/domain/user/entity/User.java
  src/main/java/com/sparta/workflowhelper/global/config/SecurityConfig.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/globalexceptions/ProjectNotFoundException.java
  src/main/java/com/sparta/workflowhelper/global/exception/customexceptions/globalexceptions/UserAlreadyExistsException.java
Labels: 🐞bug, 🔧fix, 🔨refactor

#73 🐛 BUGFIX: 카드 처음생성시 포지션 넘버 생성로직 수정
  api-test/user-test.http
  src/main/java/com/sparta/workflowhelper/domain/card/service/CardService.java
  src/test/java/com/sparta/workflowhelper/domain/auth/service/AuthServiceTest.java
Labels: 🐞bug, 🔧fix, 🔨refactor

#77 🍻 TEST: 더미데이터 init code
  src/test/java/com/sparta/workflowhelper/domain/auth/service/AuthServiceTest.java
  src/test/java/com/sparta/workflowhelper/domain/card/service/CardServiceTest.java
Labels: 📰feature, ✅test

#79 🐛 BUGFIX: addProjectMember 로직 수정
  src/main/java/com/sparta/workflowhelper/domain/project/controller/ProjectController.java
  src/main/java/com/sparta/workflowhelper/domain/project/dto/ProjectRequestDto.java
  src/main/java/com/sparta/workflowhelper/domain/project/dto/ProjectResponseDto.java
  src/main/java/com/sparta/workflowhelper/domain/project/service/ProjectService.java
  src/main/java/com/sparta/workflowhelper/domain/user/adapter/UserAdapter.java
  src/main/java/com/sparta/workflowhelper/domain/user/repository/UserRepository.java
Labels: 🐞bug, 🔧fix
